# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Ui_Login):
        Ui_Login.setObjectName("Ui_Login")
        Ui_Login.resize(555, 630)
        Ui_Login.setStyleSheet("QLineEdit{\n"
                                 # "    border:0px;    \n"
                                 # "    margin:10px;\n"
                                 # "    margin-left:10px; \n"
                                 # "    margin-right:10px;\n"
                                 "    border-bottom: 2px solid #B3B3B3;\n"
                                 "    font-family:\'Microsoft YaHei\';\n"
                                 # "    font-size:20px;\n"
                                 "    font-weight:bold;\n"
                                 "    }\n"
                                 "\n"
                                 "QLineEdit:hover{\n"
                                 "    border-bottom: 3px solid #66A3FF;\n"
                                 "    }\n"
                                 "\n"
                                 "QLineEdit:focus{\n"
                                 "    border-bottom: 3px solid #E680BD;\n"
                                 "    }\n"
                                 "\n"
                                 "QWidget#centralwidget{\n"
                                 "    background:white;\n"
                                 "    border-radius:10px;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{\n"
                                 "    text-align:right;\n"
                                 "    font-family:\'Microsoft YaHei\';\n"
                                 # "    font-size:30px;\n"
                                 "    font-weight:bold;\n"
                                 "    }\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(Ui_Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 555, 630))
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(190, 60, 161, 151))
        self.label_1.setObjectName("label_1")
        self.label_1.setStyleSheet("image: url(:/icons/rocket.png);")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 290, 31, 31))
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setStyleSheet("border-radius: 20px;\n"
                                   "background: rgba(10, 10, 10, .5);\n"
                                   )
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 390, 31, 31))
        self.label_3.setMinimumSize(QtCore.QSize(40, 40))
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        self.label_3.setStyleSheet("border-radius: 20px;\n"
                                   "background: rgba(10, 10, 10, .5);\n"
                                   )
        self.label_3.setObjectName("label_3")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 20, 80, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton.setStyleSheet("QPushButton\n"
                                        "{\n"
                                            "color:White;\n"
                                            "background: #F08080;\n"
                                            "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover\n"
                                        "{\n"
                                            "background: #FF2D2D;\n"
                                        "}\n"
                                        "QPushButton:pressed\n"
                                        "{\n"
                                            "border: 1px solid #3C3C3C!important;"
                                        "}\n"
                                        "\n"
                                        "")
        self.pushButton.setText("X")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 20, 80, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_2.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_2.setStyleSheet("QPushButton\n"
                                      "{\n"
                                          "color:White;\n"
                                          "background: #9D9D9D;\n"
                                          "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover\n"
                                      "{\n"
                                          "background: #6C6C6C;\n"
                                      "}\n"
                                      "QPushButton:pressed\n"
                                      "{\n"
                                          "border: 1px solid #3C3C3C!important;"
                                          "background:#281f1d;"
                                      "}\n"
                                      "\n")
        self.pushButton_2.setText("一")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 340, 353, 3))
        self.line.setStyleSheet("border: 3px solid 	Gray;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(160, 290, 271, 41))
        self.lineEdit_1.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_1.setStyleSheet("QLineEdit {\n"
                                      "      color: rgb(0, 0, 0);\n"
                                      "      font: 17pt \"Verdana\";\n"
                                      "      border: None;\n"
                                      "      border-bottom-color: white;\n"
                                      "      border-radius: 10px;\n"
                                      "      padding: 0 8px;\n"
                                      "}")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 390, 271, 41))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                      "      color: rgb(0,0,0);\n"
                                      "      font: 17pt \"Verdana\";\n"
                                      "      border: None;\n"
                                      "      border-radius: 10px;\n"
                                      "      padding: 0 8px;\n"
                                      "      background: rgb(255,255,255);\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(90, 440, 353, 3))
        self.line_2.setStyleSheet("border: 4px solid Gray;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 500, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "    border:0px;\n"
                                        "    height:30px;\n"
                                        "    border-radius:15px;\n"
                                        "    font-family:\'Microsoft YaHei\';\n"
                                        "    font-size:20px;\n"
                                        "    color:white;\n"
                                        "    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #a6c1ee, stop:1 #fbc2eb);\n"
                                        "    }\n"
                                        "\n"
                                        " QPushButton:hover{\n"
                                        "     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #b0cbf8, stop:1 #ffd2f0);\n"
                                        " }\n"
                                        " \n"
                                        " QPushButton:pressed{\n"
                                        "     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #92adda, stop:1 #e1aad2);\n"
                                        "     }")
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 500, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "    border:0px;\n"
                                        "    height:30px;\n"
                                        "    border-radius:15px;\n"
                                        "    font-family:\'Microsoft YaHei\';\n"
                                        "    font-size:20px;\n"
                                        "    color:white;\n"
                                        "    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
                                        "    }\n"
                                        "\n"
                                        " QPushButton:hover{\n"
                                        "     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
                                        " }\n"
                                        " \n"
                                        " QPushButton:pressed{\n"
                                        "     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
                                        "     }")
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")

        # Ui_Login.setCentralWidget(self.centralwidget)
        # self.statusbar = QtWidgets.QStatusBar(Ui_Login)
        # self.statusbar.setObjectName("statusbar")
        # Ui_Login.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_Login)
        QtCore.QMetaObject.connectSlotsByName(Ui_Login)

    def retranslateUi(self, Ui_Login):
        _translate = QtCore.QCoreApplication.translate
        Ui_Login.setWindowTitle(_translate("Ui_Login", "MainWindow"))
        # self.label_1.setText(_translate("Ui_Login", "TextLabel"))
        # self.pushButton.setText(_translate("Ui_Login", "PushButton"))
        # self.pushButton_2.setText(_translate("Ui_Login", "PushButton"))
        self.label_2.setText(
            _translate("admin", "<html><head/><body><p><img src=\":/icons/user.png\"/></p></body></html>"))
        self.label_3.setText(
            _translate("password", "<html><head/><body><p><img src=\":/icons/lock.png\"/></p></body></html>"))
        self.pushButton_3.setText(_translate("Ui_Login", "登录"))
        self.pushButton_4.setText(_translate("Ui_Login", "退出"))
        # self.label.setText(_translate("Ui_Login", "TextLabel"))
